### ISSUE TITLE
Checkbox for user to indicate if receiver should accept/reject

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn-tests#1]
In order to enable people to check filters on their inboxes, they should be able to indicate if the payload being sent is valid or not according to their constraints.

ie. [  ] My receiver should reject this notification.

If that's checked, they get a PASS for the test "Receivers SHOULD use constraints to filter unwarranted notifications from being created on the server and exposed by the Inbox." and the tests for 201 and Location are n/a

**Comment by csarven** [comment]
`checkPostResponseConstraintsUnmet` was doing this a bit. I added the form checkbox and when that's checked it will show this as a PASS. Currently using text that's mentioned in two places that's related

>Receivers which enforce constraints on the notifications <em class="rfc2119">SHOULD</em> fail to process the notification if the constraints are not met and return the appropriate <code>4xx</code> error code.

>Receivers <em class="rfc2119">SHOULD</em> use <a href="#constraints">constraints</a> to filter unwarranted notifications from being created on the server and exposed by the Inbox.
