### ISSUE TITLE
Request times out with invalid payload

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn-tests#14]
Correct behaviour is that the invalid payload is sent, and the receiver *passes* if it returns a 400 and *fails* if it returns a 2xx.

**Comment by csarven** [comment]
Resolved this at https://github.com/csarven/mayktso/commit/fcc731366f9bcc147389490619deb28670173fe7 . Should really be resolved at https://github.com/rdf-ext/rdf-parser-jsonld/issues/5 . I've only tested malformed JSON-LD and Turtle. I presume this issue was about JSON-LD
