### ISSUE TITLE
If the inbox being tested is 404, stop

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn-tests#16]
Don't bother running all the tests if the inbox is a 404. Just stop and throw an error that the inbox doesn't exist.

Right now, everything is n/a except a FAIL for POST requests and inexplicably a PASS for returning JSON-LD with message "HTTP 404, Content-Type: text/html; charset=iso-8859-1"...

**Comment by csarven** [comment]
Updated. Processes all of the tests regardless of what happens with POST. Possible that OPTIONS/HEAD/GET are okay.

Fixed the response to FAIL if GET is not 200.
