### ISSUE TITLE
Input to verify passing consumer tests

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn-tests#8]
eg..

Run your *consumer* software, and answer the following questions:

1. URL of the inbox from /tests/consumer/1 [ _______________________ ] (in header)
2. URL of the inbox from /tests/consumer/2 [ _______________________ ] (in body)
3. URLs of notifications in /1/inbox/ [ _______________________ ] (compact)
4. URLs of notifications in /2/inbox/ [ _______________________ ] (expanded)
5. Contents of notifcation /789/ [ _______________________ ] (compact)
6. Contents of notifcation /xyz/ [ _______________________ ] (expanded)

**Comment by rhiaro** [comment]
We need:

* [x] A resource which advertises an inbox in its header
* [x] A resource which advertises an inbox in its RDF body
* [x] An inbox containing 3 notifications with compact representation of ldp:contains
* [x] An inbox containing 3 notifications with expanded representation of ldp:contains
* [x] 3 notifications with compact contents
* [x] 3 notifications with expanded contents

We could do these as static files. If we use mayktso anyway, for safety, these inboxes should not be writeable.

**Comment by csarven** [comment]
I can do:
* target with Inbox header -> Inbox with compact contents -> compact notifications
* target with Inbox in RDF body (JSON-LD only?) -> Inbox with expanded contents -> expanded notifications

Any issues with that? Or need to do crazy amount of combinations?

**Comment by csarven** [comment]
Notifications in /inbox-compact/ and /inbox-expanded/ are static, and only allow methods GET, HEAD, OPTIONS. See also https://github.com/csarven/ldn-tests/issues/6#issuecomment-272664017 for Inbox with  compact representation.

**Comment by csarven** [comment]
Competed this particular issue. Not including sending its report.
