### ISSUE TITLE
Response page to verify passing sender tests

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn-tests#9]
eg..

Run your *sender* software, with this page as the target:

* Discovered inbox?
* Sent POST request?
* POST request had `Content-Type: application/ld+json` ?
* POST body was valid JSON-LD?

We need to generate pages with unique IDs as targets. Our receiver needs to recognise these unique IDs (maybe as a URL parameter on the inbox) and keep track of the content-type and payload sent to each, and the HTTP code it responded with. Then once the user has run their sender, they can refresh the 'target' page, which can find the POST request that was sent to the inbox with the corresponding unique ID, and output pass/fail for each of the bullets above.

**Comment by csarven** [comment]
"Keep track" how?
